pvp-disable-worlds:
  - world
pvp-disabled-whole-server: false
pvp-disabled-players:
  - 'Player1'
  - 'Player2'
pvp-bypass-permission: 'simplepvp.bypass'
# will notify players when they are attacked if pvp is disabled
pvp-notify-players: true

