name: Simple-PVP
version: '${project.version}'
main: com.taggernation.simplepvp.SimplePVP
authors: [ Edward ]
description: Discord/Enable PVP
website: https://taggernation.com
api-version: 1.19
commands:
  simplePVP:
    description: PvP command
    usage: /simplepvp
    aliases: [ pvp ]
